/* Write your T-SQL query statement below */
SELECT V.CUSTOMER_ID, COUNT(V.CUSTOMER_ID) AS count_no_trans
FROM VISITS V LEFT JOIN TRANSACTIONS T
ON V.VISIT_ID = T.VISIT_ID
WHERE T.AMOUNT IS NULL AND T.TRANSACTION_ID IS NULL
GROUP BY V.CUSTOMER_ID
ORDER BY V.CUSTOMER_ID;