/* Write your T-SQL query statement below */
SELECT S.STUDENT_ID, S.STUDENT_NAME, SU.SUBJECT_NAME, COUNT(E.STUDENT_ID) AS 'attended_exams'
FROM STUDENTS AS S
CROSS JOIN SUBJECTS SU
LEFT JOIN Examinations AS E ON S.STUDENT_ID = E.STUDENT_ID AND E.SUBJECT_NAME = SU.SUBJECT_NAME
GROUP BY S.STUDENT_ID, S.STUDENT_NAME, SU.SUBJECT_NAME
ORDER BY S.student_id, SU.SUBJECT_NAME;